#script for making engineering drawing stool

import FreeCAD
import Part

#creation of seat
App.ActiveDocument.addObject("Part::Box","Box")
App.ActiveDocument.ActiveObject.Label = "Cube"
App.ActiveDocument.recompute()
#providing l,b,h for seat
FreeCAD.getDocument("Unnamed").getObject("Box").Length = '7 mm'
FreeCAD.getDocument("Unnamed").getObject("Box").Width = '10 mm'
FreeCAD.getDocument("Unnamed").getObject("Box").Height = '1 mm'
#placement for seat
App.getDocument("Unnamed").Box.Placement=App.Placement(App.Vector(0,0,9),
App.Rotation(App.Vector(0,0,1),0), 
App.Vector(0,0,0))

#creation of left rear leg
App.ActiveDocument.addObject("Part::Box","Box")
App.ActiveDocument.ActiveObject.Label = "Cube"
App.ActiveDocument.recompute()
#providing l,b,h for left rear leg
FreeCAD.getDocument("Unnamed").getObject("Box001").Length = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box001").Width = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box001").Height = '10 mm'
#placement for left rear leg
App.getDocument("Unnamed").Box001.Placement=App.Placement(App.Vector(1,1,-1),
App.Rotation(App.Vector(0,0,1),0), 
App.Vector(0,0,0))

#union of seat and left rear leg
App.activeDocument().addObject("Part::MultiFuse","Fusion")
App.activeDocument().Fusion.Shapes = [App.activeDocument().Box,App.activeDocument().Box001,]

#creation of left front leg
App.ActiveDocument.recompute()
App.ActiveDocument.addObject("Part::Box","Box")
App.ActiveDocument.ActiveObject.Label = "Cube"
App.ActiveDocument.recompute()
#providing l,b,h for left front leg
FreeCAD.getDocument("Unnamed").getObject("Box002").Length = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box002").Width = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box002").Height = '10 mm'
#placement for left front leg
App.getDocument("Unnamed").Box002.Placement=App.Placement(App.Vector(5,1,-1), 
App.Rotation(App.Vector(0,0,1),0), 
App.Vector(0,0,0))

#union of left front leg & fusion
App.activeDocument().addObject("Part::MultiFuse","Fusion001")
App.activeDocument().Fusion001.Shapes = [App.activeDocument().Fusion,App.activeDocument().Box002,]

#creation of right rear leg
App.ActiveDocument.recompute()
App.ActiveDocument.addObject("Part::Box","Box")
App.ActiveDocument.ActiveObject.Label = "Cube"
App.ActiveDocument.recompute()
#providing l,b,h for right rear leg
FreeCAD.getDocument("Unnamed").getObject("Box003").Length = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box003").Width = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box003").Height = '10 mm'
#placement for right rear leg
App.getDocument("Unnamed").Box003.Placement=App.Placement(App.Vector(1,8,-1), 
App.Rotation(App.Vector(0,0,1),0), 
App.Vector(0,0,0))

#union of right rear leg & fusion001
App.activeDocument().addObject("Part::MultiFuse","Fusion002")
App.activeDocument().Fusion002.Shapes = [App.activeDocument().Fusion001,App.activeDocument().Box003,]

#creation of right front leg 
App.ActiveDocument.recompute()
App.ActiveDocument.addObject("Part::Box","Box")
App.ActiveDocument.ActiveObject.Label = "Cube"
App.ActiveDocument.recompute()
#providing l,b,h for right front leg
FreeCAD.getDocument("Unnamed").getObject("Box004").Length = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box004").Width = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box004").Height = '10 mm'
#placement for right front leg
App.getDocument("Unnamed").Box004.Placement=App.Placement(App.Vector(5,8,-1), 
App.Rotation(App.Vector(0,0,1),0), 
App.Vector(0,0,0))

#union of right front leg & fusion002
App.activeDocument().addObject("Part::MultiFuse","Fusion003")
App.activeDocument().Fusion003.Shapes = [App.activeDocument().Fusion002,App.activeDocument().Box004,]

#creation of left spindle
App.ActiveDocument.recompute()
App.ActiveDocument.addObject("Part::Box","Box")
App.ActiveDocument.ActiveObject.Label = "Cube"
App.ActiveDocument.recompute()
#providing l,b,h for left spindle
FreeCAD.getDocument("Unnamed").getObject("Box005").Length = '5 mm'
FreeCAD.getDocument("Unnamed").getObject("Box005").Width = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box005").Height = '1 mm'
#placement for left spindle
App.getDocument("Unnamed").Box005.Placement=App.Placement(App.Vector(1,1,0), 
App.Rotation(App.Vector(0,0,1),0), 
App.Vector(0,0,0))

#union of left spindle and fusion003
App.activeDocument().addObject("Part::MultiFuse","Fusion004")
App.activeDocument().Fusion004.Shapes = [App.activeDocument().Fusion003,App.activeDocument().Box005,]

#creation of right spindle
App.ActiveDocument.recompute()
App.ActiveDocument.addObject("Part::Box","Box")
App.ActiveDocument.ActiveObject.Label = "Cube"
App.ActiveDocument.recompute()
#providing l,b,h for right spindle
FreeCAD.getDocument("Unnamed").getObject("Box006").Length = '5 mm'
FreeCAD.getDocument("Unnamed").getObject("Box006").Width = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box006").Height = '1 mm'
#placement for right spindle
App.getDocument("Unnamed").Box006.Placement=App.Placement(App.Vector(1,8,0), 
App.Rotation(App.Vector(0,0,1),0), 
App.Vector(0,0,0))

#union of right spindle & fusion004
App.activeDocument().addObject("Part::MultiFuse","Fusion005")
App.activeDocument().Fusion005.Shapes = [App.activeDocument().Fusion004,App.activeDocument().Box006,]

#creation of back spindle
App.ActiveDocument.recompute()
App.ActiveDocument.addObject("Part::Box","Box")
App.ActiveDocument.ActiveObject.Label = "Cube"
App.ActiveDocument.recompute()
#providing l,b,h for back spindle
FreeCAD.getDocument("Unnamed").getObject("Box007").Length = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box007").Height = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box007").Width = '7 mm'
#placement for back spindle
App.getDocument("Unnamed").Box007.Placement=App.Placement(App.Vector(1,2,0), 
App.Rotation(App.Vector(0,0,1),0), 
App.Vector(0,0,0))

#union of back spindle & fusion005
App.activeDocument().addObject("Part::MultiFuse","Fusion006")
App.activeDocument().Fusion006.Shapes = [App.activeDocument().Fusion005,App.activeDocument().Box007,]

#creation of front spindle
App.ActiveDocument.recompute()
App.ActiveDocument.addObject("Part::Box","Box")
App.ActiveDocument.ActiveObject.Label = "Cube"
App.ActiveDocument.recompute()
#providing l,b,h for front spindle
FreeCAD.getDocument("Unnamed").getObject("Box008").Length = '1 mm'
FreeCAD.getDocument("Unnamed").getObject("Box008").Width = '8 mm'
FreeCAD.getDocument("Unnamed").getObject("Box008").Height = '1 mm'
#placement for front spindle
App.getDocument("Unnamed").Box008.Placement=App.Placement(App.Vector(5,1,0), 
App.Rotation(App.Vector(0,0,1),0), 
App.Vector(0,0,0))

#union of front spindle and fusion006
App.activeDocument().addObject("Part::MultiFuse","Fusion007")
App.activeDocument().Fusion007.Shapes = [App.activeDocument().Fusion006,App.activeDocument().Box008,]
#Gui.activeDocument().Fusion006.Visibility=False
#Gui.activeDocument().Box008.Visibility=False
#Gui.ActiveDocument.Fusion007.ShapeColor=Gui.ActiveDocument.Fusion006.ShapeColor
#Gui.ActiveDocument.Fusion007.DisplayMode=Gui.ActiveDocument.Fusion006.DisplayMode
App.ActiveDocument.recompute()
# Macro End: C:\Users\sahil\AppData\Roaming\FreeCAD\Macro\mystool.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
